spring:
  datasource:
      url: jdbc:mysql://{IP}:3306/supervision?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: xxx
      password: xxx
      driverClassName: com.mysql.jdbc.Driver
  jpa:
      database: MYSQL
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8762